### PR TITLE
Add git-sync-on-inotify

### PR DESCRIPTION
**Pull request by IvanMalison**
Wrote a simple script to perpetually monitor a git repository for changes using the inotifywait tool.

Though it is pretty short, it handles a few small gotchas that some users may not catch like:

- Not doing anything when the file changes is gitignored
- ignoring the .git directory
- redirecting output

If you don't think this is useful, feel free discard

### CODE REVIEW

**Comment by IvanMalison** [comment]
Hey @simonthum I've added something to the README. Would you consider merging?

**Comment by simonthum** [comment]
Absolutely!

**Comment by simonthum** [comment]
Fastest PR seen in my life ;)  :1st_place_medal:

**Comment by simonthum** [comment]
Thank you for keeping up with it!

**Pull request merged**
